"""paper order note

Revision ID: 765d7eee78be
Revises: ead06d834164
Create Date: 2026-09-30 09:38:47.175129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765d7eee78be'
down_revision: Union[str, Sequence[str], None] = 'ead06d834164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_orders', 'note')
    # ### end Alembic commands ###
